name = "key-website"
pages_build_output_dir = "./public"
compatibility_date = "2023-12-01"

[[kv_namespaces]]
binding = "zenkfreekeys"
id = "851338df236e4478888e1d92b4aa8e0f"
preview_id = "851338df236e4478888e1d92b4aa8e0f"

[vars]
# AD_PASS sollte in der Cloudflare-Dashboard-Oberfläche als "Secret" gesetzt werden.
# Hier nur als Platzhalter oder für lokale Entwicklung:
# AD_PASS = "dein_passwort"
